FROM store/oracle/serverjre:8
RUN yum install -y tar gzip && curl http://mirror.netinch.com/pub/apache/storm/apache-storm-1.1.0/apache-storm-1.1.0.tar.gz | tar -xvz -C /var/opt
WORKDIR /var/opt/apache-storm-1.1.0
CMD ["sh", "-c", "./bin/storm version"]
