version: '2'
services:
  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
  storm-base:
    build:
      context: ./storm-base
      dockerfile: Dockerfile.openJDK
    image: storm-base
  nimbus:
    build: ./nimbus
    image: storm-nimbus
    ports:
      - "3772-3774:3772-3774"
      - "6627:6627"
    depends_on:
      - "storm-base"
    links:
      - zookeeper:zookeeper
  supervisor:
    build: ./supervisor
    image: storm-supervisor
    ports:
      - "8000:8000"
      - "6700:6700"
      - "6701:6701"
      - "6702:6702"
      - "6703:6703"
    depends_on:
      - "storm-base"
    links:
      - zookeeper:zookeeper
      - nimbus:nimbus
  ui:
    build: ./ui
    image: storm-ui
    ports:
     - "8080:8080"
    depends_on:
      - "storm-base"
    links:
      - zookeeper:zookeeper
      - nimbus:nimbus
