version: '3'
services:
  storm-zookeeper:
    image: zookeeper
  storm-base:
    build:
      context: .
      dockerfile: Dockerfile.openJDK
    image: storm-base
    volumes:
      - /tmp:/var/opt/mytopologies
  storm-nimbus:
    image: storm-base
    command: ./bin/storm nimbus -c nimbus.seeds='["storm-nimbus"]' -c storm.zookeeper.servers='["storm-zookeeper"]'
    depends_on:
      - storm-base
  storm-supervisor:
    image: storm-base
    command: ./bin/storm supervisor -c nimbus.seeds='["storm-nimbus"]' -c storm.zookeeper.servers='["storm-zookeeper"]'
    depends_on:
      - storm-nimbus
  storm-ui:
    image: storm-base
    command: ./bin/storm ui -c nimbus.seeds='["storm-nimbus"]' -c storm.zookeeper.servers='["storm-zookeeper"]'
    ports:
      - "8080:8080"
    depends_on:
      - storm-base
      - storm-zookeeper
      - storm-nimbus
