version: '2'
services:
  zookeeper:
    image: zookeeper
  storm-base:
    build:
      context: .
      dockerfile: Dockerfile.openJDK
    image: storm-base
    volumes:
      - /opt:/var/opt/mytopologies
  nimbus:
    image: storm-base
    container_name: nimbus
    command: ./bin/storm nimbus -c nimbus.seeds='["nimbus"]' -c storm.zookeeper.servers='["zookeeper"]'
    depends_on:
      - storm-base
    links:
      - zookeeper:zookeeper
  supervisor:
    image: storm-base
    container_name: supervisor
    command: ./bin/storm supervisor -c nimbus.seeds='["nimbus"]' -c storm.zookeeper.servers='["zookeeper"]'
    depends_on:
      - nimbus
    links:
      - zookeeper:zookeeper
      - nimbus:nimbus
  ui:
    image: storm-base
    container_name: ui
    command: ./bin/storm ui -c nimbus.seeds='["nimbus"]' -c storm.zookeeper.servers='["zookeeper"]'
    depends_on:
      - storm-base
    links:
      - zookeeper:zookeeper
      - nimbus:nimbus
